version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    container_name: matomo_mariadb
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
      - TZ=Asia/Taipei
    volumes:
      - 'mariadb_data:/matomo'
  matomo:
    image: 'bitnami/matomo:3'
    container_name: mysql
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Taipei
      - MATOMO_ENABLE_PROXY_URI_HEADER=yes
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    volumes:
      - 'matomo_data:/bitnami'
      - $PWD/config.ini.php:/bitnami/matomo/config/config.ini.php
volumes:
  mariadb_data:
    driver: local
  matomo_data:
    driver: local
