version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    container_name: matomo_mariadb
    #network_mode:  "host"
    environment:
      - MARIADB_USER=bn_matomo
      - MARIADB_DATABASE=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_EXTRA_FLAGS=--max_allowed_packet=64MB
      - TZ=Asia/Taipei
    volumes:
#      - 'mariadb_data:/matomo'
       - $PWD/data/db:/matomo
  matomo:
    image: 'bitnami/matomo:3'
    container_name: matomo
    environment:
      - MARIADB_HOST=mariadb
 #     - MARIADB_HOST=localhost
      - MARIADB_PORT_NUMBER=3306
      - MATOMO_DATABASE_USER=bn_matomo
      - MATOMO_DATABASE_NAME=bitnami_matomo
      - ALLOW_EMPTY_PASSWORD=yes
      - TZ=Asia/Taipei
#      - MATOMO_EMAIL="user@testmatomo.pjm.iisigroup.com"
#      - MATOMO_WEBSITE_HOST="https://testmatomo.pjm.iisigroup.com"
#      - MATOMO_ENABLE_PROXY_URI_HEADER=yes
    ports:
      - '80:80'
      - '443:443'
#    network_mode:  "host"
    depends_on:
      - mariadb
    volumes:
#       - $PWD/server.key:/opt/bitnami/apache/conf/bitnami/certs/server.key
#       - $PWD/server.crt:/opt/bitnami/apache/conf/bitnami/certs/server.crt
#       - $PWD/httpd.conf:/opt/bitnami/apache/conf/httpd.conf
#       - $PWD/bitnami.conf:/opt/bitnami/apache/conf/bitnami/bitnami.conf
#       - $PWD/bitnami-ssl.conf:/opt/bitnami/apache/conf/bitnami/bitnami-ssl.conf
       - $PWD/data/matomo:/bitnami
#      - 'matomo_data:/bitnami'
#      - $PWD/config.ini.php:/bitnami/matomo/config/config.ini.php
#
#volumes:
#  mariadb_data:
#    driver: local
#  matomo_data:
#    driver: local
